### PR TITLE
Improved icons and System Tray Menu Order

### PR DESCRIPTION
**Pull request by Thjj**
Icon now in 1:1 aspect ratio
Added icons in smaller resolution
Better order in tray menu (Exit on bottom)

### CODE REVIEW

**Review by rnayabed — CHANGES_REQUESTED** [review]
`macos-icon.icns` and `windows-icon.ico` are required for the executable installer binaries.

**Review by rnayabed — CHANGES_REQUESTED** [review]
`macos-icon.icns` and `windows-icon.ico` are required for the executable installer binaries.

**Comment by Thjj** [comment]
> `macos-icon.icns` and `windows-icon.ico` are required for the executable installer binaries.

`macos-icon.icns` and `windows-icon.ico` are where they should be. They only have a 1:1 aspect ratio and for windows and macos I added icons in lower resolution.

**Comment by rnayabed** [comment]
Oops, i just realised that they are not deleted, but reduced in size. Can you enable and run the workflows on your fork, build jpackage binaries and then try out the installer binaries and see whether the icon quality was degraded in windows/mac systems (app icon, and installer icon)?

**Comment by Thjj** [comment]
Yes, I'm going to try it

**Comment by rnayabed** [comment]
I forked your fork, into another fork, ran the workflows there, tried it on a Windows 10 VM, and it looks good :+1: 

image
*Old Icon (Left) vs New Icon (Right)*

image
*Old Icon (Top) vs New Icon (Buttom)*

image
image
*New Icon (Top) vs Old Icon (Bottom)*


Ill try running on a MacOS VM and an Ubuntu VM later today. If you have a MacOS and Ubuntu/RPM based system yourself, please post a similar comparison like this for them.

I run Manjaro, so neither RPM nor DEB work on my system. I tried the zip, the logos looked fine.

**Comment by Thjj** [comment]
This is what it looks like on the Ubuntu 20.04 VM, and it looks almost the same.
Taskbar
_New Icon (Top) vs Old Icon (Bottom)_
App browse new
App browse old
_New Icon (Top) vs Old Icon (Bottom)_

**Review by rnayabed — APPROVED** [review]
looks ok

**Pull request merged**
